### PR TITLE
preview: safe communication

### PR DESCRIPTION
**Pull request by Trolldemorted**
I had a look whether safe (only one command at a time) and enum-ed communication is possible with a manageable amount of work. It really is quite a lot because we would have to touch every bg->ui message, but allowing only one command at a time is quite easy (just use a mutex and try_lock in every ui handler, get rid of refcelled-receivers as a nice bonus). If you like it I can continue, if you have comments I'd much like to hear them!

### CODE REVIEW

**Comment by Frodo45127** [comment]
Wait a second....
``` Rust
lazy_static! {
    static ref UI_CONTEXT: Mutex<Option<UIContext>> = Mutex::new(None);
}
```
Does this allow to use stuff that depends on runtime data as static? Because currently `rpfm_path` and `games_supported` vars have to be cloned all over the place because they depend on a function's result that has to be calculated at runtime and `const fn` is not stable. That'll make using them far easier.

**Comment by Trolldemorted** [comment]
This is the lazy way of dealing with static data, yes. To access it you do
```rust
let mutex_guard = match UI_CONTEXT.try_lock() {
    Ok(mutex_guard) => mutex_guard,
    Err(_) => {
        eprintln!("failed to get ui lock");
        return;
    }
};
let ui_context: &UIContext = &mutex_guard.as_ref().unwrap();
```

`mutex_guard` could even be mutable and yield a mutable reference to its content. If you don't like lazy_static you could use `Arc<Mutex<UIContext>>` instead and just clone the arc into every closure, and try to lock it within the closure with the parameter instead of the statc field.

**Comment by Frodo45127** [comment]
Mmmm how would a guard like that work in a situation were one action calls another action? For example, when saving, if there is no file to save, the save slot triggers the "save as" slot. There are quite a few like that.

**Comment by Trolldemorted** [comment]
>Mmmm how would a guard like that work in a situation were one action calls another action? For example, when saving, if there is no file to save, the save slot triggers the "save as" slot. There are quite a few like that.

If you want that something you call can lock the mutex, you have to drop it before calling. But is that necessary? Can't you just define a function that does "save as foo" and call it in both handlers while you hold the lock? You can pass a (mutable) reference of the UIContext you get from the mutex to anything you call directly.

>Also, how would it work with stuff that has to be triggered yes or yes, like the checks to know if an action of the context menu is applicable to whatever it ended selected in the treeview when the selected item is deleted?

I am not sure what you mean. If the "delete item" handler has to refresh the UI state (e.g. to enable/disable buttons because a different item is selected) it can do that after the deletion finished and before it returns. If qt triggers an "item selection changed" event while the "delete item" handler is running `try_lock` will return an error and the handler will exit early. If you move the "update UI state for new selected item"-stuff in a dedicated function you can just call it from both handlers.

**Comment by Frodo45127** [comment]
Closing as part of the 2.0 cleanup as this is already implemented into the program.

**Pull request closed without merging**
