### PR TITLE
use twa_pack_lib to read and write pack files

### PR DESCRIPTION
**Pull request by Trolldemorted**
Looks like it works!

### Advantages:
- safe parsing in a separated lib
- real bitmasks instead of binary operations
- relatively small commit, as soon as serde-serialization is thrown out you can throw away the wrapper structs
- enums for the pfh file version and type

### Disadvantages:
- no lazy-loading at the moment (but we can implement that if we want it)
- I don't own a twa game so I could not test whether features like siege ai patching works, but I might get my hands on a rome2 installation soon

### CODE REVIEW

**Comment by Frodo45127** [comment]
> I don't own a twa game so I could not test whether features like siege ai patching works, but I might get my hands on a rome2 installation soon

SiegeAI Patching only works for Warhammer games, not for historical ones.

Ok, after some thinking, some asking, and taking a more open look at the code, I've decided to put this on hold. It's not rejected, as the lib is in the end going to be used in RPFM, but testing the lib separately with the unpacker yesterday I managed to crash it, and testing RPFM with the pull-request today in a quick test (just opening PackFiles) I found the type of the PackFile in the UI is broken (it doesn't get updated when you open a PackFile), and I want to test more in deep the adding/deleting stuff, as there may be some things broken there too, due to the path changes and RPFM dealing sometimes with slightly altered paths.

Some questions:
- Is there any special reason for keeping the paths of the PackFile as a full string instead a vector? I mean, apart of not needing to put them together when encoding. Not splitting them there means they have to be splitted in a ton of places instead.
- Can we change the lib to `tw_pack_lib`? I mean, if it's supporting more than just Arena, doesn't have too much sense to have the `a` there.
- In `packedfile/mod.rs`, line 397, there is this: 
``` Rust
else { name = format!("{}_{}_{}.tsv", split_path[1], split_path.last().unwrap().to_owned(), index); }
```
Is there any reason why we want to know the folder of a loc when exporting? As long as the locs are inside `text` folder, they can be in whatever structure you want.
- The error messages can be a bit more... descriptive, but that can be fixed in the future, so it's not a problem.
- Is there any specific reason (other than less code to change) to not remove the current `PackFileHeader` and `PackFileExtraData` and include their info into the `PackFileView`?
 - What's the benefit of using bitmask instead of booleans? For what I saw, it's just more code without an appreaciable benefit.
- Any reason to not use buffers when reading/writing PackFiles from disk? Last time I checked, using them reduced reading/writing times by 2 to 3 times.
- Correct me if I'm wrong but, checking the `PackFileView::read()` function.... you parse the entire PackFile to ram, then get the PackedFiles? That means that, at one point, the entire raw data of the PackFile AND all the PackedFiles decoded exists in memory, isn't? Doing that, can cause the data.pack (one that many modders open frequently) to eat 8GB of ram in that moment, causing the entire system to slow down/hang in systems with 8GB of Ram or less. I know it because it happened in older versions of RPFM. Since then, all PackFiles are decoded while reading them from disk. 

Apart of that, there is one big blocker: lazy-loading. Currently in RPFM is imprescindible to not load 4GB of data to ram when you want to add a table from data.pack (usually, tables are here and this PackFile is 3-4GB) to your mod. Before the "Read-Only" mode landed in RPFM, adding files from another PackFile was a tremendous pain that could even slow down your PC to a crawl. There is no need to implement it with save capabilities. Currently only read capabilities are required. Without it, that feature and the db references stuff (which is currently not used since the Qt port, but it's going to be used) are regressed.

That's more or less what I found for now. I'll finish the channel stuff so we can remove that wrapper and see after that what needs to be done to not make this very painful.

**Comment by Trolldemorted** [comment]
>Is there any special reason for keeping the paths of the PackFile as a full string instead a vector? I mean, apart of not needing to put them together when encoding. Not splitting them there means they have to be splitted in a ton of places instead.

pack_lib is supposed to be a generic library, and splitting the string into a vec is quite rpfm-specific. We can implement the split-borrowing in a dedicated trait, though!

>Can we change the lib to tw_pack_lib? I mean, if it's supporting more than just Arena, doesn't have too much sense to have the a there.

Good point, we might want to change the organization name to tw_modding too. twa_unpack can unpack wh and rome packs too, so its name doesn't fit either.

>In packedfile/mod.rs, line 397, there is this:
[...]
Is there any reason why we want to know the folder of a loc when exporting? As long as the locs are inside text folder, they can be in whatever structure you want.

I don't know, it's what the current [develop master](https://github.com/Frodo45127/rpfm/blob/develop/src/packedfile/mod.rs#L303) does. Too much information can't hurt, I suppose?

>The error messages can be a bit more... descriptive, but that can be fixed in the future, so it's not a problem.

👍 we also need better docs on docs.io

>Is there any specific reason (other than less code to change) to not remove the current PackFileHeader and PackFileExtraData and include their info into the PackFileView

Yes and no -  I wanted to open a PR with the least possible changed code, but you still might want a dedicated `UIPackFile` struct which you send to the UI thread. PackFileHeader and PackFileExtraData combined are a few bytes, a PackFileView can be up to 4 GB you would have to clone/serialize.

>What's the benefit of using bitmask instead of booleans? For what I saw, it's just more code without an appreaciable benefit.

It depends on how you count code - to check if a bit is set it's `.is_foo_set` vs `.contains(CONSTANT)`, where the latter uses more letters but the same amount if lines. The process of making bools from the u32 and vice versa is almost 0, though.

>Any reason to not use buffers when reading/writing PackFiles from disk? Last time I checked, using them reduced reading/writing times by 2 to 3 times.

Will come with lazy-loading support.

>Correct me if I'm wrong but, checking the PackFileView::read() function.... you parse the entire PackFile to ram, then get the PackedFiles? That means that, at one point, the entire raw data of the PackFile AND all the PackedFiles decoded exists in memory, isn't? Doing that, can cause the data.pack (one that many modders open frequently) to eat 8GB of ram in that moment, causing the entire system to slow down/hang in systems with 8GB of Ram or less. I know it because it happened in older versions of RPFM. Since then, all PackFiles are decoded while reading them from disk.

You are right, I have started working on lazy-loading. twa_pack_lib 0.1.12 no longer requires the entire file to be buffered in memory. True lazy-loading is not yet there, but it is better than before.

**Comment by Trolldemorted** [comment]
Accidentally sent String instead of Vec<String> to the UI for paths, that explains the panics when editing packed files. Should be fixed now.

**Comment by Frodo45127** [comment]
> pack_lib is supposed to be a generic library, and splitting the string into a vec is quite rpfm-specific. We can implement the split-borrowing in a dedicated trait, though!

And can't we just split all the paths after receiving the data from the lib instead of having to split the path/ join it in every place they're used? That'll will simplify the patch a lot.

> I don't know, it's what the current develop master does. Too much information can't hurt, I suppose?

That line is for DB tables. The one I told you about was for Loc files, about 60 or 70 lines below. Yeah, it can't hurt, but changing for the sake of changing can. So that has to go back as it can potentially cause exported files with duplicate names like `locfile_locfile_1.tsv`.

> Yes and no - I wanted to open a PR with the least possible changed code, but you still might want a dedicated UIPackFile struct which you send to the UI thread. PackFileHeader and PackFileExtraData combined are a few bytes, a PackFileView can be up to 4 GB you would have to clone/serialize.

And why is the data that can take up to 4GB in the same object that has data that may be cloned/serialized. Wouldn't be easier to return that data in a separate object?

> It depends on how you count code - to check if a bit is set it's .is_foo_set vs .contains(CONSTANT), where the latter uses more letters but the same amount if lines. The process of making bools from the u32 and vice versa is almost 0, though.
 
I mean this:
- With bitflags: 
``` Rust
pack_file_decoded.bitmask.set(PFHFlags::HAS_INDEX_WITH_TIMESTAMPS, state);
```
- With bools: 
``` Rust
pack_file_decoded.header.index_includes_timestamp = state
```
One requires you to use a function, specifing what bit you want to change. The other... just changes it. Looks simpler and more intuitive for me.

**Comment by Frodo45127** [comment]
> The problem is that offering a vec is highly rpfm-specific, and would require additional documentation that it contains the dir/filenames in a certain order. I'd rather create a dedicated struct in rpfm which consumes the pack_lib packedfile, or implement a dedicated rpfm-packedfile trait.

> It has not - PackFileHeader and PackFileExtraData are moved/cloned/serialized (and PackFileView is not, because it contains the data), and they are the same structs as before. Creating a separate object with only the data the UI needs is what I meant with "creating a UIPackFile".

No, I mean... At this point, wouldn't be easier to just have an PackFile struct like the one there is currently in RPFM (a bit more simplified though) and just map the PackFileView to it when decoding, and the inverse when encoding? I mean, PackFileHeader and PackFileExtraData are already there, and the PackedFile struct's path needs to be changed to be usable in RPFM. Good things are the transition will be faaaar simpler. Bad things are that RPFM will have to keep the extra functions like `add_packedfile()`, `is_editable()`,... Instead of leveraging that to the lib.

Also, offering a vec is not really specific to RPFM. If you want to do any modification to part of the path, like changing a folder, or moving the packedfile, it's easier with a vec where you can change/remove/add individual parts. Other that for seeing the full path, some comparisons and a few operations, there is no really much sense on using a string for it.

> Yeah, they need the same amount of lines but the former needs more letters. But with the former every user will immediately realize there is a bitmask underneath the hood (and should be able to jump to the constant once RLS gets better), the latter requires additional code to convert an u32 to a set of bools and back. I don't want unnecessary abstractions in the pack pib, but we can convert the bitmask to a set of bools in rpfm - but that will result in more code.

More code the user wont see. For the user, he doesn't need to know if there is a bitmask, bool, or a completely different system unless is interested in helping with the lib. For an user it's far simpler to see "this can be true or false" than "this is a bitmask in the bit X that we can set to true or false". It's easier to understand for someone external to the lib. But that's just an opinion anyway.

**Comment by Trolldemorted** [comment]
>No, I mean... At this point, wouldn't be easier to just have an PackFile struct like the one there is currently in RPFM (a bit more simplified though) and just map the PackFileView to it when decoding, and the inverse when encoding? I mean, PackFileHeader and PackFileExtraData are already there, and the PackedFile struct's path needs to be changed to be usable in RPFM. Good things are the transition will be faaaar simpler. Bad things are that RPFM will have to keep the extra functions like add_packedfile(), is_editable(),... Instead of leveraging that to the lib.

If you merge PackFileHeader and PackFileExtraData into one struct, you can throw out 1 command, 1 response, the corresponding handling, and you don't need any middle~men~structs - the UI needs a dedicated struct anyway.

>Also, offering a vec is not really specific to RPFM. If you want to do any modification to part of the path, like changing a folder, or moving the packedfile, it's easier with a vec where you can change/remove/add individual parts. Other that for seeing the full path, some comparisons and a few operations, there is no really much sense on using a string for it.

Well you want to use vecs, but others might want to use PathBufs or are custom solution - that's not something I'd impose that far down in the stack (pack_lib is just a shallow layer after all). Did I understand the code correctly that you sometimes include the pack file's filename in the vec? If so, I'd recommend that you introduce dedicated types so that they become easily distinguishable.

But we can mimic the PackFile<->PackFileView relation and add a PackedFileView which contains the PackedFile, the split interior path, and everything else rpfm might require.

>"this can be true or false" than "this is a bitmask in the bit X that we can set to true or false".

Isn't that virtually the same? We can unpack the bitmask in /packfile/packfile.rs, but a well-abstracted bitmask shouldn't hurt anyone :)

>That line is for DB tables.

fixed!

**Comment by Trolldemorted** [comment]
Rebased to the current develop. Since serde is gone, the wrapper structs are gone too 🎉

**Comment by Trolldemorted** [comment]
Lazy-loading is finally in an acceptable shape! 🎉A call to pack_lib::parse_pack for twa's rigidmodels.pack (1.8GB) takes about 1.5s now. Downside is that every access to a PackedFile's data may return an error (since it uses I/O and the file might be corrupted), so I used unwraps everywhere for now since I didn't want to touch your error handling in this commit.

>Sure, those two can be merged, but I still think the data (current PackFileData) should still be in a separate place. So we don't have to pass 500MB of data to the UI when we just want the header.

Sure, packed file contents should only be moved when they are requested, and even in that case we should move an arc and not clone the entire buffer. pack_lib's PackedFile needs a better clone (which does not clone the underlying vector), but we are not far away from that if we want it (but we definitely should do that in a separate pr).

>Ok, then. Then in RPFM that "translation" from string to vec and back has to be moved to the reading/saving functions, instead of being done on demand all over the place.

Done!

>No problem with making it a custom type

Sounds out of scope for this PR, but we still might want to do it sometime

>Virtually, yes. Visually, no. It's easier to understand at first sight "this is true or false" than "this is a bitmask in byte X". It's more simple for someone who don't have any idea what a bitmask is (like me a few months ago).

We can keep the "unpacking" to bools while building the structs for the UI, but I don't think pack_lib should, as it stops users from using syntatic sougar like or-ing values (`PFHFlags::HAS_BIG_HEADER | PFHFlags::HAS_INDEX_WITH_TIMESTAMPS`).


Since rebasing this branch is quite cumbersome due to its size, we should merge it as soon as possible. Now that lazyloading is here, are there any other showstoppers we have to take care of? If not, I'd add support for the pf file list in the header to pack_lib (I hope I can find a .pack that uses it so I can test it) and rename everyting to tw_* instead of twa_*.

Minor things like using the PFHVersion enum everywhere and the like should go into separate commits imo, since this one is large enough.

**Comment by Frodo45127** [comment]
> We can keep the "unpacking" to bools while building the structs for the UI, but I don't think pack_lib should, as it stops users from using syntatic sougar like or-ing values (PFHFlags::HAS_BIG_HEADER | PFHFlags::HAS_INDEX_WITH_TIMESTAMPS).

What's the difference between `if PFHFlags::HAS_BIG_HEADER | PFHFlags::HAS_INDEX_WITH_TIMESTAMPS {}` and `if pack.has_extended_header || pack.index_has_timestamps {}`?

>Since rebasing this branch is quite cumbersome due to its size, we should merge it as soon as possible. 

I just rebased it locally to do some testing, and there are no conflicts or problems. It'll be merged when it works, because currently there are plenty of things broken with this patch.

I already reported some of the issues that seem to come from bugs in the lib in the lib's repo, so we can leave this for issues with the patch itself, not within the lib. Among the broken things, there are:
- Saving generates corrupted PackFiles (part seems to be issues in the lib, part with data that's provided wrong from the UI).
- When opening a PackFile, the type doesn't get updated (it uses the old header, instead the data from the lib).
- When opening a PackFile of a game whose path is in the settings, the PackFile takes a lot of time to open (tested with a Rome 2 PackFile, and it took 22 seconds for a 36mb PackFile). The problem seems to be somewhere in the load of the data PackFiles (for dependencies) as without those PackFiles it doesn't take that long.
- Why is the PackedFile's data sent in an `Result<Arc<Vec<u8>>>`? I understand the result, but the arc?
- You seem to have replaced completely the old way of opening PackFiles with lazy-loading.... Currently, lazy-loading is used only in read-only PackFiles due to a bug in Warhammer 2 Assembly Kit that tends to delete PackFiles, if you have both the Assembly kit and RPFM/PFM open. By loading the entire PackFile to memory, we can still save it if the bug gets triggered. That's why I said that the blocker was read-only lazy-loading, and there was no need to do it for saving. We can use it, but not until the bug gets fixed by CA. Otherwise RPFM would be able to delete entire PackFiles, like PFM does. And that's something I don't want.

I'll check it more this week and see if I can fix some of the UI problems, and find why the hell does it take so long to load the PackFiles. For now that's what I've found.

**Comment by Trolldemorted** [comment]
>What's the difference between if PFHFlags::HAS_BIG_HEADER | PFHFlags::HAS_INDEX_WITH_TIMESTAMPS {} and if pack.has_extended_header || pack.index_has_timestamps {}?

In ifs it's no huge difference (except from writing the bitmask<->bool code), but you can create bitmasks like `let foo = PFHFlags::HAS_BIG_HEADER | PFHFlags::HAS_INDEX_WITH_TIMESTAMPS` and call contains() and friends on them, which imo is awesome syntactic sugar.

>Saving generates corrupted PackFiles (part seems to be issues in the lib, part with data that's provided wrong from the UI).

Found a bug with warhammer 2's packs (see tw_pack_lib issue), fixed in 0.1.16!

>When opening a PackFile, the type doesn't get updated (it uses the old header, instead the data from the lib).

Nice catch, was a bug in tw_pack_lib, fixed in 0.1.17!

>When opening a PackFile of a game whose path is in the settings, the PackFile takes a lot of time to open (tested with a Rome 2 PackFile, and it took 22 seconds for a 36mb PackFile). The problem seems to be somewhere in the load of the data PackFiles (for dependencies) as without those PackFiles it doesn't take that long.

I have a rome2 installation here, what do I have to do to test it? Select rome2, set the tw rome2 path, open a certain pack file?

>Why is the PackedFile's data sent in an Result<Arc<Vec<u8>>>? I understand the result, but the arc?

Because this way you don't have to clone the data as soon as I fix https://github.com/TotalWar-Modding/tw_pack_lib/issues/1, but instead clone only a safe reference to the data.

>You seem to have replaced completely the old way of opening PackFiles with lazy-loading.... Currently, lazy-loading is used only in read-only PackFiles due to a bug in Warhammer 2 Assembly Kit that tends to delete PackFiles, if you have both the Assembly kit and RPFM/PFM open. By loading the entire PackFile to memory, we can still save it if the bug gets triggered. That's why I said that the blocker was read-only lazy-loading, and there was no need to do it for saving. We can use it, but not until the bug gets fixed by CA. Otherwise RPFM would be able to delete entire PackFiles, like PFM does. And that's something I don't want.

At some point it just goes insane and deletes your files? That is ugly indeed. To ensure a packed file is in memory, all you have to do is call get_data at least once - so we could loop over every packed file on loading just like it is done on saving.

**Comment by Frodo45127** [comment]
>In ifs it's no huge difference (except from writing the bitmask<->bool code), but you can create bitmasks like let foo = PFHFlags::HAS_BIG_HEADER | PFHFlags::HAS_INDEX_WITH_TIMESTAMPS and call contains() and friends on them, which imo is awesome syntactic sugar.

Ok then. Not a great fan of syntax sugar (Sometimes it makes simple code hard to understand for the untrained eye) but ok.

> I have a rome2 installation here, what do I have to do to test it? Select rome2, set the tw rome2 path, open a certain pack file?

Go to `PackFile/Preferences`, configure the Rome 2 path, hit save, then open a Rome 2 PackFile. It takes 20-22 seconds for me with this patch, 1-5 without it.

> Because this way you don't have to clone the data as soon as I fix TotalWar-Modding/tw_pack_lib#1, but instead clone only a safe reference to the data.

What I mean is, what is the benefit over using a reference with `&` (or clone when we want an editable copy)? Just reading the docs, it's just an thread-safe Rc, but more costly and I don't really understand his use. Actually, all the `Rc<RefCell<>>` currently in the code are there as an "heritage" of when this program used GTK-RS, because that was how you passed stuff to the closures there. The only thing I understand about them is that it allows to bypass some compiler rules, but in exchange they can trigger CTDs in runtime.

> At some point it just goes insane and deletes your files? That is ugly indeed. To ensure a packed file is in memory, all you have to do is call get_data at least once - so we could loop over every packed file on loading just like it is done on saving.

It was one of the bugs that made me start this program. And yeah, that's an acceptable workaround.

**Comment by Trolldemorted** [comment]
>What I mean is, what is the benefit over using a reference with & (or clone when we want an editable copy)? Just reading the docs, it's just an thread-safe Rc, but more costly and I don't really understand his use. Actually, all the Rc<RefCell<>> currently in the code are there as an "heritage" of when this program used GTK-RS, because that was how you passed stuff to the closures there. The only thing I understand about them is that it allows to bypass some compiler rules, but in exchange they can trigger CTDs in runtime.

If you clone an Arc<Vec<u8>> you are more or less just incrementing the arc's internal reference counter. Both the original arc and the new clone own the vector and you can move them into closures, whereas using `&Vec<u8>` would require you to meet lifetime requirements: You must prove the compiler that the reference does not outlive the vector, which you can't since you are passing that reference to a thread that is not guaranteed to terminate before the vector goes out of scope.

**Comment by Trolldemorted** [comment]
>So it can be used to make the compiler accept references in cases when it usually doesn't accept them. Ok, I think I undesrtand it now.

Mind that references in rust are always &s and they always borrow its content - an `Arc` is just a `Box` which you can clone and which implements `Send` and `Sync`, and like the box it actually *owns* the data it points to - [this means you can leak memory if you have cyclic references, since rust has no garbage collector](https://gist.github.com/imos/daf2fdbab8f33bd05a51fc12f017b579).

**Comment by Frodo45127** [comment]
Closing as part of the 2.0 cleanup. I have to admit this was quite a learning experience that has serve me a lot.

**Pull request closed without merging**
